name = "Tylo"
uuid = "e9ed47d0-8750-4009-b91d-3679011a846b"
authors = ["AntonOresten <antonoresten@proton.me> and contributors"]
version = "0.0.1"

[workspace]
projects = ["test", "docs"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
cuTile = "0dea8319-8c4a-4662-a73d-20234d115b9a"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
ChainRulesCoreExt = "ChainRulesCore"
MooncakeExt = ["Mooncake", "ChainRulesCore"]

[sources]
cuTile = {rev = "main", url = "https://github.com/JuliaGPU/cuTile.jl"}

[compat]
Adapt = "4"
CUDACore = "6"
ChainRulesCore = "1.26.1"
Mooncake = "0.5.32"
cuTile = "0.3"
julia = "1.11"
